# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_id.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_id.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61mera_id.proto\x12\x04ltpb*\x8a\x01\n\x08\x43\x61meraID\x12\x06\n\x02\x41\x31\x10\x00\x12\x06\n\x02\x41\x32\x10\x01\x12\x06\n\x02\x41\x33\x10\x02\x12\x06\n\x02\x41\x34\x10\x03\x12\x06\n\x02\x41\x35\x10\x04\x12\x06\n\x02\x42\x31\x10\x05\x12\x06\n\x02\x42\x32\x10\x06\x12\x06\n\x02\x42\x33\x10\x07\x12\x06\n\x02\x42\x34\x10\x08\x12\x06\n\x02\x42\x35\x10\t\x12\x06\n\x02\x43\x31\x10\n\x12\x06\n\x02\x43\x32\x10\x0b\x12\x06\n\x02\x43\x33\x10\x0c\x12\x06\n\x02\x43\x34\x10\r\x12\x06\n\x02\x43\x35\x10\x0e\x12\x06\n\x02\x43\x36\x10\x0f'
)

_CAMERAID = _descriptor.EnumDescriptor(
  name='CameraID',
  full_name='ltpb.CameraID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='A1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='A2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='A3', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='A4', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='A5', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B1', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B2', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B3', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B4', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B5', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C1', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C2', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C3', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C4', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C5', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C6', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=26,
  serialized_end=164,
)
_sym_db.RegisterEnumDescriptor(_CAMERAID)

CameraID = enum_type_wrapper.EnumTypeWrapper(_CAMERAID)
A1 = 0
A2 = 1
A3 = 2
A4 = 3
A5 = 4
B1 = 5
B2 = 6
B3 = 7
B4 = 8
B5 = 9
C1 = 10
C2 = 11
C3 = 12
C4 = 13
C5 = 14
C6 = 15


DESCRIPTOR.enum_types_by_name['CameraID'] = _CAMERAID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
