# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: color_calibration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import matrix3x3f_pb2 as matrix3x3f__pb2
import point3f_pb2 as point3f__pb2
import point2f_pb2 as point2f__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='color_calibration.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63olor_calibration.proto\x12\x04ltpb\x1a\x10matrix3x3f.proto\x1a\rpoint3f.proto\x1a\rpoint2f.proto\"\xb8\x05\n\x10\x43olorCalibration\x12\x33\n\x04type\x18\x01 \x02(\x0e\x32%.ltpb.ColorCalibration.IlluminantType\x12(\n\x0e\x66orward_matrix\x18\x02 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12&\n\x0c\x63olor_matrix\x18\x03 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12\x10\n\x08rg_ratio\x18\x04 \x02(\x02\x12\x10\n\x08\x62g_ratio\x18\x05 \x02(\x02\x12#\n\x0cmacbeth_data\x18\x06 \x03(\x0b\x32\r.ltpb.Point3F\x12%\n\x0eilluminant_spd\x18\x07 \x03(\x0b\x32\r.ltpb.Point2F\x12:\n\rspectral_data\x18\x08 \x01(\x0b\x32#.ltpb.ColorCalibration.SpectralData\x1a\xc7\x01\n\x0cSpectralData\x12\x41\n\x06\x66ormat\x18\x01 \x02(\x0e\x32\x31.ltpb.ColorCalibration.SpectralData.ChannelFormat\x12@\n\x0c\x63hannel_data\x18\x02 \x03(\x0b\x32*.ltpb.ColorCalibration.SpectralSensitivity\"2\n\rChannelFormat\x12\x08\n\x04MONO\x10\x00\x12\x07\n\x03RGB\x10\x01\x12\x0e\n\nBAYER_RGGB\x10\x02\x1a\x43\n\x13SpectralSensitivity\x12\r\n\x05start\x18\x01 \x02(\r\x12\x0b\n\x03\x65nd\x18\x02 \x02(\r\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x02\x42\x02\x10\x01\"b\n\x0eIlluminantType\x12\x05\n\x01\x41\x10\x00\x12\x07\n\x03\x44\x35\x30\x10\x01\x12\x07\n\x03\x44\x36\x35\x10\x02\x12\x07\n\x03\x44\x37\x35\x10\x03\x12\x06\n\x02\x46\x32\x10\x04\x12\x06\n\x02\x46\x37\x10\x05\x12\x07\n\x03\x46\x31\x31\x10\x06\x12\x08\n\x04TL84\x10\x07\x12\x0b\n\x07UNKNOWN\x10\x63'
  ,
  dependencies=[matrix3x3f__pb2.DESCRIPTOR,point3f__pb2.DESCRIPTOR,point2f__pb2.DESCRIPTOR,])



_COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT = _descriptor.EnumDescriptor(
  name='ChannelFormat',
  full_name='ltpb.ColorCalibration.SpectralData.ChannelFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MONO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RGB', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAYER_RGGB', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=559,
  serialized_end=609,
)
_sym_db.RegisterEnumDescriptor(_COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT)

_COLORCALIBRATION_ILLUMINANTTYPE = _descriptor.EnumDescriptor(
  name='IlluminantType',
  full_name='ltpb.ColorCalibration.IlluminantType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='A', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='D50', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='D65', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='D75', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='F2', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='F7', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='F11', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TL84', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=8, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=680,
  serialized_end=778,
)
_sym_db.RegisterEnumDescriptor(_COLORCALIBRATION_ILLUMINANTTYPE)


_COLORCALIBRATION_SPECTRALDATA = _descriptor.Descriptor(
  name='SpectralData',
  full_name='ltpb.ColorCalibration.SpectralData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='ltpb.ColorCalibration.SpectralData.format', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_data', full_name='ltpb.ColorCalibration.SpectralData.channel_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=609,
)

_COLORCALIBRATION_SPECTRALSENSITIVITY = _descriptor.Descriptor(
  name='SpectralSensitivity',
  full_name='ltpb.ColorCalibration.SpectralSensitivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='ltpb.ColorCalibration.SpectralSensitivity.start', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='ltpb.ColorCalibration.SpectralSensitivity.end', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ltpb.ColorCalibration.SpectralSensitivity.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=678,
)

_COLORCALIBRATION = _descriptor.Descriptor(
  name='ColorCalibration',
  full_name='ltpb.ColorCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ltpb.ColorCalibration.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forward_matrix', full_name='ltpb.ColorCalibration.forward_matrix', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color_matrix', full_name='ltpb.ColorCalibration.color_matrix', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rg_ratio', full_name='ltpb.ColorCalibration.rg_ratio', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bg_ratio', full_name='ltpb.ColorCalibration.bg_ratio', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='macbeth_data', full_name='ltpb.ColorCalibration.macbeth_data', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='illuminant_spd', full_name='ltpb.ColorCalibration.illuminant_spd', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectral_data', full_name='ltpb.ColorCalibration.spectral_data', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COLORCALIBRATION_SPECTRALDATA, _COLORCALIBRATION_SPECTRALSENSITIVITY, ],
  enum_types=[
    _COLORCALIBRATION_ILLUMINANTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=778,
)

_COLORCALIBRATION_SPECTRALDATA.fields_by_name['format'].enum_type = _COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT
_COLORCALIBRATION_SPECTRALDATA.fields_by_name['channel_data'].message_type = _COLORCALIBRATION_SPECTRALSENSITIVITY
_COLORCALIBRATION_SPECTRALDATA.containing_type = _COLORCALIBRATION
_COLORCALIBRATION_SPECTRALDATA_CHANNELFORMAT.containing_type = _COLORCALIBRATION_SPECTRALDATA
_COLORCALIBRATION_SPECTRALSENSITIVITY.containing_type = _COLORCALIBRATION
_COLORCALIBRATION.fields_by_name['type'].enum_type = _COLORCALIBRATION_ILLUMINANTTYPE
_COLORCALIBRATION.fields_by_name['forward_matrix'].message_type = matrix3x3f__pb2._MATRIX3X3F
_COLORCALIBRATION.fields_by_name['color_matrix'].message_type = matrix3x3f__pb2._MATRIX3X3F
_COLORCALIBRATION.fields_by_name['macbeth_data'].message_type = point3f__pb2._POINT3F
_COLORCALIBRATION.fields_by_name['illuminant_spd'].message_type = point2f__pb2._POINT2F
_COLORCALIBRATION.fields_by_name['spectral_data'].message_type = _COLORCALIBRATION_SPECTRALDATA
_COLORCALIBRATION_ILLUMINANTTYPE.containing_type = _COLORCALIBRATION
DESCRIPTOR.message_types_by_name['ColorCalibration'] = _COLORCALIBRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ColorCalibration = _reflection.GeneratedProtocolMessageType('ColorCalibration', (_message.Message,), {

  'SpectralData' : _reflection.GeneratedProtocolMessageType('SpectralData', (_message.Message,), {
    'DESCRIPTOR' : _COLORCALIBRATION_SPECTRALDATA,
    '__module__' : 'color_calibration_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.ColorCalibration.SpectralData)
    })
  ,

  'SpectralSensitivity' : _reflection.GeneratedProtocolMessageType('SpectralSensitivity', (_message.Message,), {
    'DESCRIPTOR' : _COLORCALIBRATION_SPECTRALSENSITIVITY,
    '__module__' : 'color_calibration_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.ColorCalibration.SpectralSensitivity)
    })
  ,
  'DESCRIPTOR' : _COLORCALIBRATION,
  '__module__' : 'color_calibration_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.ColorCalibration)
  })
_sym_db.RegisterMessage(ColorCalibration)
_sym_db.RegisterMessage(ColorCalibration.SpectralData)
_sym_db.RegisterMessage(ColorCalibration.SpectralSensitivity)


_COLORCALIBRATION_SPECTRALSENSITIVITY.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
