# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dead_pixel_map.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dead_pixel_map.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x65\x61\x64_pixel_map.proto\x12\x04ltpb\"U\n\x0c\x44\x65\x61\x64PixelMap\x12\x13\n\x0b\x64\x61ta_offset\x18\x01 \x02(\x04\x12\x11\n\tdata_size\x18\x02 \x02(\r\x12\x1d\n\x15\x62lack_level_threshold\x18\x03 \x01(\x02'
)




_DEADPIXELMAP = _descriptor.Descriptor(
  name='DeadPixelMap',
  full_name='ltpb.DeadPixelMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_offset', full_name='ltpb.DeadPixelMap.data_offset', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_size', full_name='ltpb.DeadPixelMap.data_size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='black_level_threshold', full_name='ltpb.DeadPixelMap.black_level_threshold', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['DeadPixelMap'] = _DEADPIXELMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeadPixelMap = _reflection.GeneratedProtocolMessageType('DeadPixelMap', (_message.Message,), {
  'DESCRIPTOR' : _DEADPIXELMAP,
  '__module__' : 'dead_pixel_map_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.DeadPixelMap)
  })
_sym_db.RegisterMessage(DeadPixelMap)


# @@protoc_insertion_point(module_scope)
