# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_temp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='device_temp.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65vice_temp.proto\x12\x04ltpb\"k\n\nDeviceTemp\x12\x10\n\x08sensor_1\x18\x01 \x01(\x11\x12\x10\n\x08sensor_2\x18\x02 \x01(\x11\x12\x10\n\x08sensor_3\x18\x03 \x01(\x11\x12\x10\n\x08sensor_4\x18\x04 \x01(\x11\x12\x15\n\rflex_sensor_1\x18\x05 \x01(\x11'
)




_DEVICETEMP = _descriptor.Descriptor(
  name='DeviceTemp',
  full_name='ltpb.DeviceTemp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_1', full_name='ltpb.DeviceTemp.sensor_1', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_2', full_name='ltpb.DeviceTemp.sensor_2', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_3', full_name='ltpb.DeviceTemp.sensor_3', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_4', full_name='ltpb.DeviceTemp.sensor_4', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flex_sensor_1', full_name='ltpb.DeviceTemp.flex_sensor_1', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['DeviceTemp'] = _DEVICETEMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceTemp = _reflection.GeneratedProtocolMessageType('DeviceTemp', (_message.Message,), {
  'DESCRIPTOR' : _DEVICETEMP,
  '__module__' : 'device_temp_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.DeviceTemp)
  })
_sym_db.RegisterMessage(DeviceTemp)


# @@protoc_insertion_point(module_scope)
