# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gps_data.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0egps_data.proto\x12\x04ltpb\"\xa4\x06\n\x07GPSData\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0b\n\x03\x64op\x18\x04 \x01(\x01\x12\"\n\x05track\x18\x05 \x01(\x0b\x32\x13.ltpb.GPSData.Track\x12&\n\x07heading\x18\x06 \x01(\x0b\x32\x15.ltpb.GPSData.Heading\x12(\n\x08\x61ltitude\x18\x07 \x01(\x0b\x32\x16.ltpb.GPSData.Altitude\x12\r\n\x05speed\x18\x08 \x01(\x01\x12\x39\n\x11processing_method\x18\t \x01(\x0e\x32\x1e.ltpb.GPSData.ProcessingMethod\x1a\x41\n\x05Track\x12\r\n\x05value\x18\x01 \x02(\x01\x12)\n\x03ref\x18\x02 \x02(\x0e\x32\x1c.ltpb.GPSData.ReferenceNorth\x1a\x43\n\x07Heading\x12\r\n\x05value\x18\x01 \x02(\x01\x12)\n\x03ref\x18\x02 \x02(\x0e\x32\x1c.ltpb.GPSData.ReferenceNorth\x1aG\n\x08\x41ltitude\x12\r\n\x05value\x18\x01 \x02(\x01\x12,\n\x03ref\x18\x02 \x02(\x0e\x32\x1f.ltpb.GPSData.ReferenceAltitude\"\xc1\x01\n\x10ProcessingMethod\x12\x1d\n\x19PROCESSING_METHOD_UNKNOWN\x10\x00\x12\x19\n\x15PROCESSING_METHOD_GPS\x10\x01\x12\x1c\n\x18PROCESSING_METHOD_CELLID\x10\x02\x12\x1a\n\x16PROCESSING_METHOD_WLAN\x10\x03\x12\x1c\n\x18PROCESSING_METHOD_MANUAL\x10\x04\x12\x1b\n\x17PROCESSING_METHOD_FUSED\x10\x05\"H\n\x0eReferenceNorth\x12\x1c\n\x18REFERENCE_NORTH_MAGNETIC\x10\x00\x12\x18\n\x14REFERENCE_NORTH_TRUE\x10\x01\"5\n\x11ReferenceAltitude\x12 \n\x1cREFERENCE_ALTITUDE_SEA_LEVEL\x10\x00'
)



_GPSDATA_PROCESSINGMETHOD = _descriptor.EnumDescriptor(
  name='ProcessingMethod',
  full_name='ltpb.GPSData.ProcessingMethod',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_GPS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_CELLID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_WLAN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_MANUAL', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_FUSED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=507,
  serialized_end=700,
)
_sym_db.RegisterEnumDescriptor(_GPSDATA_PROCESSINGMETHOD)

_GPSDATA_REFERENCENORTH = _descriptor.EnumDescriptor(
  name='ReferenceNorth',
  full_name='ltpb.GPSData.ReferenceNorth',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_NORTH_MAGNETIC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_NORTH_TRUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=702,
  serialized_end=774,
)
_sym_db.RegisterEnumDescriptor(_GPSDATA_REFERENCENORTH)

_GPSDATA_REFERENCEALTITUDE = _descriptor.EnumDescriptor(
  name='ReferenceAltitude',
  full_name='ltpb.GPSData.ReferenceAltitude',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_ALTITUDE_SEA_LEVEL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=776,
  serialized_end=829,
)
_sym_db.RegisterEnumDescriptor(_GPSDATA_REFERENCEALTITUDE)


_GPSDATA_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='ltpb.GPSData.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSData.Track.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSData.Track.ref', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=362,
)

_GPSDATA_HEADING = _descriptor.Descriptor(
  name='Heading',
  full_name='ltpb.GPSData.Heading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSData.Heading.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSData.Heading.ref', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=431,
)

_GPSDATA_ALTITUDE = _descriptor.Descriptor(
  name='Altitude',
  full_name='ltpb.GPSData.Altitude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSData.Altitude.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSData.Altitude.ref', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=504,
)

_GPSDATA = _descriptor.Descriptor(
  name='GPSData',
  full_name='ltpb.GPSData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ltpb.GPSData.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ltpb.GPSData.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ltpb.GPSData.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dop', full_name='ltpb.GPSData.dop', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track', full_name='ltpb.GPSData.track', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='ltpb.GPSData.heading', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ltpb.GPSData.altitude', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ltpb.GPSData.speed', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processing_method', full_name='ltpb.GPSData.processing_method', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GPSDATA_TRACK, _GPSDATA_HEADING, _GPSDATA_ALTITUDE, ],
  enum_types=[
    _GPSDATA_PROCESSINGMETHOD,
    _GPSDATA_REFERENCENORTH,
    _GPSDATA_REFERENCEALTITUDE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=829,
)

_GPSDATA_TRACK.fields_by_name['ref'].enum_type = _GPSDATA_REFERENCENORTH
_GPSDATA_TRACK.containing_type = _GPSDATA
_GPSDATA_HEADING.fields_by_name['ref'].enum_type = _GPSDATA_REFERENCENORTH
_GPSDATA_HEADING.containing_type = _GPSDATA
_GPSDATA_ALTITUDE.fields_by_name['ref'].enum_type = _GPSDATA_REFERENCEALTITUDE
_GPSDATA_ALTITUDE.containing_type = _GPSDATA
_GPSDATA.fields_by_name['track'].message_type = _GPSDATA_TRACK
_GPSDATA.fields_by_name['heading'].message_type = _GPSDATA_HEADING
_GPSDATA.fields_by_name['altitude'].message_type = _GPSDATA_ALTITUDE
_GPSDATA.fields_by_name['processing_method'].enum_type = _GPSDATA_PROCESSINGMETHOD
_GPSDATA_PROCESSINGMETHOD.containing_type = _GPSDATA
_GPSDATA_REFERENCENORTH.containing_type = _GPSDATA
_GPSDATA_REFERENCEALTITUDE.containing_type = _GPSDATA
DESCRIPTOR.message_types_by_name['GPSData'] = _GPSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPSData = _reflection.GeneratedProtocolMessageType('GPSData', (_message.Message,), {

  'Track' : _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATA_TRACK,
    '__module__' : 'gps_data_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSData.Track)
    })
  ,

  'Heading' : _reflection.GeneratedProtocolMessageType('Heading', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATA_HEADING,
    '__module__' : 'gps_data_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSData.Heading)
    })
  ,

  'Altitude' : _reflection.GeneratedProtocolMessageType('Altitude', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATA_ALTITUDE,
    '__module__' : 'gps_data_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSData.Altitude)
    })
  ,
  'DESCRIPTOR' : _GPSDATA,
  '__module__' : 'gps_data_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.GPSData)
  })
_sym_db.RegisterMessage(GPSData)
_sym_db.RegisterMessage(GPSData.Track)
_sym_db.RegisterMessage(GPSData.Heading)
_sym_db.RegisterMessage(GPSData.Altitude)


# @@protoc_insertion_point(module_scope)
