# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hot_pixel_map.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hot_pixel_map.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13hot_pixel_map.proto\x12\x04ltpb\"\xf5\x01\n\x0bHotPixelMap\x12\x33\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32%.ltpb.HotPixelMap.HotPixelMeasurement\x1a\xb0\x01\n\x13HotPixelMeasurement\x12\x13\n\x0b\x64\x61ta_offset\x18\x01 \x02(\x04\x12\x11\n\tdata_size\x18\x02 \x02(\r\x12\x15\n\rdata_exposure\x18\x03 \x02(\r\x12\x1a\n\x12sensor_temparature\x18\x04 \x02(\x05\x12\x13\n\x0bsensor_gain\x18\x05 \x02(\x02\x12\x16\n\x0epixel_variance\x18\x06 \x01(\x02\x12\x11\n\tthreshold\x18\x07 \x01(\x02'
)




_HOTPIXELMAP_HOTPIXELMEASUREMENT = _descriptor.Descriptor(
  name='HotPixelMeasurement',
  full_name='ltpb.HotPixelMap.HotPixelMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_offset', full_name='ltpb.HotPixelMap.HotPixelMeasurement.data_offset', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_size', full_name='ltpb.HotPixelMap.HotPixelMeasurement.data_size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_exposure', full_name='ltpb.HotPixelMap.HotPixelMeasurement.data_exposure', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_temparature', full_name='ltpb.HotPixelMap.HotPixelMeasurement.sensor_temparature', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_gain', full_name='ltpb.HotPixelMap.HotPixelMeasurement.sensor_gain', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixel_variance', full_name='ltpb.HotPixelMap.HotPixelMeasurement.pixel_variance', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='ltpb.HotPixelMap.HotPixelMeasurement.threshold', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=275,
)

_HOTPIXELMAP = _descriptor.Descriptor(
  name='HotPixelMap',
  full_name='ltpb.HotPixelMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ltpb.HotPixelMap.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HOTPIXELMAP_HOTPIXELMEASUREMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=275,
)

_HOTPIXELMAP_HOTPIXELMEASUREMENT.containing_type = _HOTPIXELMAP
_HOTPIXELMAP.fields_by_name['data'].message_type = _HOTPIXELMAP_HOTPIXELMEASUREMENT
DESCRIPTOR.message_types_by_name['HotPixelMap'] = _HOTPIXELMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotPixelMap = _reflection.GeneratedProtocolMessageType('HotPixelMap', (_message.Message,), {

  'HotPixelMeasurement' : _reflection.GeneratedProtocolMessageType('HotPixelMeasurement', (_message.Message,), {
    'DESCRIPTOR' : _HOTPIXELMAP_HOTPIXELMEASUREMENT,
    '__module__' : 'hot_pixel_map_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.HotPixelMap.HotPixelMeasurement)
    })
  ,
  'DESCRIPTOR' : _HOTPIXELMAP,
  '__module__' : 'hot_pixel_map_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.HotPixelMap)
  })
_sym_db.RegisterMessage(HotPixelMap)
_sym_db.RegisterMessage(HotPixelMap.HotPixelMeasurement)


# @@protoc_insertion_point(module_scope)
