# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hw_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_type_pb2 as sensor__type__pb2
import camera_id_pb2 as camera__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hw_info.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rhw_info.proto\x12\x04ltpb\x1a\x11sensor_type.proto\x1a\x0f\x63\x61mera_id.proto\"\x9b\x05\n\x12\x43\x61meraModuleHwInfo\x12\x1a\n\x02id\x18\x01 \x02(\x0e\x32\x0e.ltpb.CameraID\x12 \n\x06sensor\x18\x02 \x02(\x0e\x32\x10.ltpb.SensorType\x12=\n\x04lens\x18\x03 \x01(\x0e\x32!.ltpb.CameraModuleHwInfo.LensType:\x0cLENS_UNKNOWN\x12]\n\x0fmirror_actuator\x18\x04 \x01(\x0e\x32+.ltpb.CameraModuleHwInfo.MirrorActuatorType:\x17MIRROR_ACTUATOR_UNKNOWN\x12\x43\n\x06mirror\x18\x05 \x01(\x0e\x32#.ltpb.CameraModuleHwInfo.MirrorType:\x0eMIRROR_UNKNOWN\"a\n\x08LensType\x12\x10\n\x0cLENS_UNKNOWN\x10\x00\x12\x0f\n\x0bLENS_SHOWIN\x10\x01\x12\x0f\n\x0bLENS_LARGAN\x10\x02\x12\x0e\n\nLENS_SUNNY\x10\x03\x12\x11\n\rLENS_KANTATSU\x10\x04\"J\n\x12MirrorActuatorType\x12\x1b\n\x17MIRROR_ACTUATOR_UNKNOWN\x10\x00\x12\x17\n\x13MIRROR_ACTUATOR_PZT\x10\x01\"U\n\nMirrorType\x12\x12\n\x0eMIRROR_UNKNOWN\x10\x00\x12\x19\n\x15MIRROR_DIELECTRIC_SNX\x10\x01\x12\x18\n\x14MIRROR_SILVER_ZUISHO\x10\x02\"^\n\x10LensActuatorType\x12\x19\n\x15LENS_ACTUATOR_UNKNOWN\x10\x00\x12\x18\n\x14LENS_ACTUATOR_SHICOH\x10\x01\x12\x15\n\x11LENS_ACTUATOR_PZT\x10\x02\"\xfa\x02\n\x06HwInfo\x12(\n\x06\x63\x61mera\x18\x01 \x03(\x0b\x32\x18.ltpb.CameraModuleHwInfo\x12\x34\n\x05\x66lash\x18\x02 \x01(\x0e\x32\x16.ltpb.HwInfo.FlashType:\rFLASH_UNKNOWN\x12.\n\x03tof\x18\x03 \x01(\x0e\x32\x14.ltpb.HwInfo.ToFType:\x0bTOF_UNKNOWN\x12%\n\x05model\x18\x04 \x01(\x0e\x32\x16.ltpb.HwInfo.ModelType\x12\x14\n\x0cmanufacturer\x18\x05 \x01(\t\"6\n\tFlashType\x12\x11\n\rFLASH_UNKNOWN\x10\x00\x12\x16\n\x12\x46LASH_OSRAM_CBLPM1\x10\x01\"2\n\x07ToFType\x12\x0f\n\x0bTOF_UNKNOWN\x10\x00\x12\x16\n\x12TOF_STMICRO_VL53L0\x10\x01\"7\n\tModelType\x12\x0c\n\x08MODEL_P1\x10\x00\x12\x0e\n\nMODEL_P1_1\x10\x01\x12\x0c\n\x08MODEL_P2\x10\x02'
  ,
  dependencies=[sensor__type__pb2.DESCRIPTOR,camera__id__pb2.DESCRIPTOR,])



_CAMERAMODULEHWINFO_LENSTYPE = _descriptor.EnumDescriptor(
  name='LensType',
  full_name='ltpb.CameraModuleHwInfo.LensType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LENS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_SHOWIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_LARGAN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_SUNNY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_KANTATSU', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=371,
  serialized_end=468,
)
_sym_db.RegisterEnumDescriptor(_CAMERAMODULEHWINFO_LENSTYPE)

_CAMERAMODULEHWINFO_MIRRORACTUATORTYPE = _descriptor.EnumDescriptor(
  name='MirrorActuatorType',
  full_name='ltpb.CameraModuleHwInfo.MirrorActuatorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIRROR_ACTUATOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIRROR_ACTUATOR_PZT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=470,
  serialized_end=544,
)
_sym_db.RegisterEnumDescriptor(_CAMERAMODULEHWINFO_MIRRORACTUATORTYPE)

_CAMERAMODULEHWINFO_MIRRORTYPE = _descriptor.EnumDescriptor(
  name='MirrorType',
  full_name='ltpb.CameraModuleHwInfo.MirrorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIRROR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIRROR_DIELECTRIC_SNX', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIRROR_SILVER_ZUISHO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=546,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_CAMERAMODULEHWINFO_MIRRORTYPE)

_CAMERAMODULEHWINFO_LENSACTUATORTYPE = _descriptor.EnumDescriptor(
  name='LensActuatorType',
  full_name='ltpb.CameraModuleHwInfo.LensActuatorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LENS_ACTUATOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_ACTUATOR_SHICOH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LENS_ACTUATOR_PZT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=633,
  serialized_end=727,
)
_sym_db.RegisterEnumDescriptor(_CAMERAMODULEHWINFO_LENSACTUATORTYPE)

_HWINFO_FLASHTYPE = _descriptor.EnumDescriptor(
  name='FlashType',
  full_name='ltpb.HwInfo.FlashType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLASH_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLASH_OSRAM_CBLPM1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=945,
  serialized_end=999,
)
_sym_db.RegisterEnumDescriptor(_HWINFO_FLASHTYPE)

_HWINFO_TOFTYPE = _descriptor.EnumDescriptor(
  name='ToFType',
  full_name='ltpb.HwInfo.ToFType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOF_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOF_STMICRO_VL53L0', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1001,
  serialized_end=1051,
)
_sym_db.RegisterEnumDescriptor(_HWINFO_TOFTYPE)

_HWINFO_MODELTYPE = _descriptor.EnumDescriptor(
  name='ModelType',
  full_name='ltpb.HwInfo.ModelType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODEL_P1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_P1_1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODEL_P2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1053,
  serialized_end=1108,
)
_sym_db.RegisterEnumDescriptor(_HWINFO_MODELTYPE)


_CAMERAMODULEHWINFO = _descriptor.Descriptor(
  name='CameraModuleHwInfo',
  full_name='ltpb.CameraModuleHwInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ltpb.CameraModuleHwInfo.id', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='ltpb.CameraModuleHwInfo.sensor', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lens', full_name='ltpb.CameraModuleHwInfo.lens', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror_actuator', full_name='ltpb.CameraModuleHwInfo.mirror_actuator', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror', full_name='ltpb.CameraModuleHwInfo.mirror', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CAMERAMODULEHWINFO_LENSTYPE,
    _CAMERAMODULEHWINFO_MIRRORACTUATORTYPE,
    _CAMERAMODULEHWINFO_MIRRORTYPE,
    _CAMERAMODULEHWINFO_LENSACTUATORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=727,
)


_HWINFO = _descriptor.Descriptor(
  name='HwInfo',
  full_name='ltpb.HwInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera', full_name='ltpb.HwInfo.camera', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flash', full_name='ltpb.HwInfo.flash', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tof', full_name='ltpb.HwInfo.tof', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='ltpb.HwInfo.model', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='ltpb.HwInfo.manufacturer', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HWINFO_FLASHTYPE,
    _HWINFO_TOFTYPE,
    _HWINFO_MODELTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=730,
  serialized_end=1108,
)

_CAMERAMODULEHWINFO.fields_by_name['id'].enum_type = camera__id__pb2._CAMERAID
_CAMERAMODULEHWINFO.fields_by_name['sensor'].enum_type = sensor__type__pb2._SENSORTYPE
_CAMERAMODULEHWINFO.fields_by_name['lens'].enum_type = _CAMERAMODULEHWINFO_LENSTYPE
_CAMERAMODULEHWINFO.fields_by_name['mirror_actuator'].enum_type = _CAMERAMODULEHWINFO_MIRRORACTUATORTYPE
_CAMERAMODULEHWINFO.fields_by_name['mirror'].enum_type = _CAMERAMODULEHWINFO_MIRRORTYPE
_CAMERAMODULEHWINFO_LENSTYPE.containing_type = _CAMERAMODULEHWINFO
_CAMERAMODULEHWINFO_MIRRORACTUATORTYPE.containing_type = _CAMERAMODULEHWINFO
_CAMERAMODULEHWINFO_MIRRORTYPE.containing_type = _CAMERAMODULEHWINFO
_CAMERAMODULEHWINFO_LENSACTUATORTYPE.containing_type = _CAMERAMODULEHWINFO
_HWINFO.fields_by_name['camera'].message_type = _CAMERAMODULEHWINFO
_HWINFO.fields_by_name['flash'].enum_type = _HWINFO_FLASHTYPE
_HWINFO.fields_by_name['tof'].enum_type = _HWINFO_TOFTYPE
_HWINFO.fields_by_name['model'].enum_type = _HWINFO_MODELTYPE
_HWINFO_FLASHTYPE.containing_type = _HWINFO
_HWINFO_TOFTYPE.containing_type = _HWINFO
_HWINFO_MODELTYPE.containing_type = _HWINFO
DESCRIPTOR.message_types_by_name['CameraModuleHwInfo'] = _CAMERAMODULEHWINFO
DESCRIPTOR.message_types_by_name['HwInfo'] = _HWINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraModuleHwInfo = _reflection.GeneratedProtocolMessageType('CameraModuleHwInfo', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAMODULEHWINFO,
  '__module__' : 'hw_info_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.CameraModuleHwInfo)
  })
_sym_db.RegisterMessage(CameraModuleHwInfo)

HwInfo = _reflection.GeneratedProtocolMessageType('HwInfo', (_message.Message,), {
  'DESCRIPTOR' : _HWINFO,
  '__module__' : 'hw_info_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.HwInfo)
  })
_sym_db.RegisterMessage(HwInfo)


# @@protoc_insertion_point(module_scope)
