# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix4x4f.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix4x4f.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10matrix4x4f.proto\x12\x04ltpb\"\xdc\x01\n\nMatrix4x4F\x12\x0b\n\x03x00\x18\x01 \x02(\x02\x12\x0b\n\x03x01\x18\x02 \x02(\x02\x12\x0b\n\x03x02\x18\x03 \x02(\x02\x12\x0b\n\x03x03\x18\x04 \x02(\x02\x12\x0b\n\x03x10\x18\x05 \x02(\x02\x12\x0b\n\x03x11\x18\x06 \x02(\x02\x12\x0b\n\x03x12\x18\x07 \x02(\x02\x12\x0b\n\x03x13\x18\x08 \x02(\x02\x12\x0b\n\x03x20\x18\t \x02(\x02\x12\x0b\n\x03x21\x18\n \x02(\x02\x12\x0b\n\x03x22\x18\x0b \x02(\x02\x12\x0b\n\x03x23\x18\x0c \x02(\x02\x12\x0b\n\x03x30\x18\r \x02(\x02\x12\x0b\n\x03x31\x18\x0e \x02(\x02\x12\x0b\n\x03x32\x18\x0f \x02(\x02\x12\x0b\n\x03x33\x18\x10 \x02(\x02'
)




_MATRIX4X4F = _descriptor.Descriptor(
  name='Matrix4x4F',
  full_name='ltpb.Matrix4x4F',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x00', full_name='ltpb.Matrix4x4F.x00', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x01', full_name='ltpb.Matrix4x4F.x01', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x02', full_name='ltpb.Matrix4x4F.x02', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x03', full_name='ltpb.Matrix4x4F.x03', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x10', full_name='ltpb.Matrix4x4F.x10', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x11', full_name='ltpb.Matrix4x4F.x11', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x12', full_name='ltpb.Matrix4x4F.x12', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x13', full_name='ltpb.Matrix4x4F.x13', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x20', full_name='ltpb.Matrix4x4F.x20', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x21', full_name='ltpb.Matrix4x4F.x21', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x22', full_name='ltpb.Matrix4x4F.x22', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x23', full_name='ltpb.Matrix4x4F.x23', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x30', full_name='ltpb.Matrix4x4F.x30', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x31', full_name='ltpb.Matrix4x4F.x31', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x32', full_name='ltpb.Matrix4x4F.x32', index=14,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x33', full_name='ltpb.Matrix4x4F.x33', index=15,
      number=16, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=247,
)

DESCRIPTOR.message_types_by_name['Matrix4x4F'] = _MATRIX4X4F
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matrix4x4F = _reflection.GeneratedProtocolMessageType('Matrix4x4F', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX4X4F,
  '__module__' : 'matrix4x4f_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.Matrix4x4F)
  })
_sym_db.RegisterMessage(Matrix4x4F)


# @@protoc_insertion_point(module_scope)
