# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror_system.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import matrix3x3f_pb2 as matrix3x3f__pb2
import point3f_pb2 as point3f__pb2
import range2f_pb2 as range2f__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mirror_system.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13mirror_system.proto\x12\x04ltpb\x1a\x10matrix3x3f.proto\x1a\rpoint3f.proto\x1a\rrange2f.proto\"\x94\x03\n\x0cMirrorSystem\x12+\n\x14real_camera_location\x18\x01 \x02(\x0b\x32\r.ltpb.Point3F\x12\x31\n\x17real_camera_orientation\x18\x02 \x02(\x0b\x32\x10.ltpb.Matrix3x3F\x12$\n\rrotation_axis\x18\x03 \x02(\x0b\x32\r.ltpb.Point3F\x12-\n\x16point_on_rotation_axis\x18\x04 \x02(\x0b\x32\r.ltpb.Point3F\x12\x37\n/distance_mirror_plane_to_point_on_rotation_axis\x18\x05 \x02(\x02\x12\x34\n\x1dmirror_normal_at_zero_degrees\x18\x06 \x02(\x0b\x32\r.ltpb.Point3F\x12\x19\n\x11\x66lip_img_around_x\x18\x07 \x02(\x08\x12)\n\x12mirror_angle_range\x18\x08 \x02(\x0b\x32\r.ltpb.Range2F\x12\x1a\n\x12reprojection_error\x18\t \x01(\x02\"\xe6\x05\n\x15MirrorActuatorMapping\x12K\n\x13transformation_type\x18\x01 \x02(\x0e\x32..ltpb.MirrorActuatorMapping.TransformationType\x12\x1e\n\x16\x61\x63tuator_length_offset\x18\x02 \x02(\x02\x12\x1d\n\x15\x61\x63tuator_length_scale\x18\x03 \x02(\x02\x12\x1b\n\x13mirror_angle_offset\x18\x04 \x02(\x02\x12\x1a\n\x12mirror_angle_scale\x18\x05 \x02(\x02\x12N\n\x17\x61\x63tuator_angle_pair_vec\x18\x06 \x03(\x0b\x32-.ltpb.MirrorActuatorMapping.ActuatorAnglePair\x12\x43\n\x0fquadratic_model\x18\x07 \x02(\x0b\x32*.ltpb.MirrorActuatorMapping.QuadraticModel\x12 \n\x18\x61ngle_to_hall_code_error\x18\x08 \x01(\x02\x12 \n\x18hall_code_to_angle_error\x18\t \x01(\x02\x12&\n\x0fhall_code_range\x18\n \x01(\x0b\x32\r.ltpb.Range2F\x1a\x35\n\x11\x41\x63tuatorAnglePair\x12\x11\n\thall_code\x18\x01 \x02(\x05\x12\r\n\x05\x61ngle\x18\x02 \x02(\x02\x1a\x8d\x01\n\x0eQuadraticModel\x12\"\n\x1ause_rplus_for_left_segment\x18\x01 \x02(\x08\x12#\n\x1buse_rplus_for_right_segment\x18\x02 \x02(\x08\x12\x18\n\x10inflection_value\x18\x03 \x02(\x02\x12\x18\n\x0cmodel_coeffs\x18\x04 \x03(\x02\x42\x02\x10\x01\"@\n\x12TransformationType\x12\x16\n\x12MEAN_STD_NORMALIZE\x10\x00\x12\x12\n\x0eTAN_HALF_THETA\x10\x01'
  ,
  dependencies=[matrix3x3f__pb2.DESCRIPTOR,point3f__pb2.DESCRIPTOR,range2f__pb2.DESCRIPTOR,])



_MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE = _descriptor.EnumDescriptor(
  name='TransformationType',
  full_name='ltpb.MirrorActuatorMapping.TransformationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MEAN_STD_NORMALIZE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TAN_HALF_THETA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1163,
  serialized_end=1227,
)
_sym_db.RegisterEnumDescriptor(_MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE)


_MIRRORSYSTEM = _descriptor.Descriptor(
  name='MirrorSystem',
  full_name='ltpb.MirrorSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='real_camera_location', full_name='ltpb.MirrorSystem.real_camera_location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real_camera_orientation', full_name='ltpb.MirrorSystem.real_camera_orientation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_axis', full_name='ltpb.MirrorSystem.rotation_axis', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_on_rotation_axis', full_name='ltpb.MirrorSystem.point_on_rotation_axis', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance_mirror_plane_to_point_on_rotation_axis', full_name='ltpb.MirrorSystem.distance_mirror_plane_to_point_on_rotation_axis', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror_normal_at_zero_degrees', full_name='ltpb.MirrorSystem.mirror_normal_at_zero_degrees', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flip_img_around_x', full_name='ltpb.MirrorSystem.flip_img_around_x', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror_angle_range', full_name='ltpb.MirrorSystem.mirror_angle_range', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reprojection_error', full_name='ltpb.MirrorSystem.reprojection_error', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=482,
)


_MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR = _descriptor.Descriptor(
  name='ActuatorAnglePair',
  full_name='ltpb.MirrorActuatorMapping.ActuatorAnglePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hall_code', full_name='ltpb.MirrorActuatorMapping.ActuatorAnglePair.hall_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='ltpb.MirrorActuatorMapping.ActuatorAnglePair.angle', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=964,
  serialized_end=1017,
)

_MIRRORACTUATORMAPPING_QUADRATICMODEL = _descriptor.Descriptor(
  name='QuadraticModel',
  full_name='ltpb.MirrorActuatorMapping.QuadraticModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_rplus_for_left_segment', full_name='ltpb.MirrorActuatorMapping.QuadraticModel.use_rplus_for_left_segment', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_rplus_for_right_segment', full_name='ltpb.MirrorActuatorMapping.QuadraticModel.use_rplus_for_right_segment', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inflection_value', full_name='ltpb.MirrorActuatorMapping.QuadraticModel.inflection_value', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_coeffs', full_name='ltpb.MirrorActuatorMapping.QuadraticModel.model_coeffs', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1020,
  serialized_end=1161,
)

_MIRRORACTUATORMAPPING = _descriptor.Descriptor(
  name='MirrorActuatorMapping',
  full_name='ltpb.MirrorActuatorMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transformation_type', full_name='ltpb.MirrorActuatorMapping.transformation_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actuator_length_offset', full_name='ltpb.MirrorActuatorMapping.actuator_length_offset', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actuator_length_scale', full_name='ltpb.MirrorActuatorMapping.actuator_length_scale', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror_angle_offset', full_name='ltpb.MirrorActuatorMapping.mirror_angle_offset', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirror_angle_scale', full_name='ltpb.MirrorActuatorMapping.mirror_angle_scale', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actuator_angle_pair_vec', full_name='ltpb.MirrorActuatorMapping.actuator_angle_pair_vec', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quadratic_model', full_name='ltpb.MirrorActuatorMapping.quadratic_model', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle_to_hall_code_error', full_name='ltpb.MirrorActuatorMapping.angle_to_hall_code_error', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hall_code_to_angle_error', full_name='ltpb.MirrorActuatorMapping.hall_code_to_angle_error', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hall_code_range', full_name='ltpb.MirrorActuatorMapping.hall_code_range', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR, _MIRRORACTUATORMAPPING_QUADRATICMODEL, ],
  enum_types=[
    _MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=1227,
)

_MIRRORSYSTEM.fields_by_name['real_camera_location'].message_type = point3f__pb2._POINT3F
_MIRRORSYSTEM.fields_by_name['real_camera_orientation'].message_type = matrix3x3f__pb2._MATRIX3X3F
_MIRRORSYSTEM.fields_by_name['rotation_axis'].message_type = point3f__pb2._POINT3F
_MIRRORSYSTEM.fields_by_name['point_on_rotation_axis'].message_type = point3f__pb2._POINT3F
_MIRRORSYSTEM.fields_by_name['mirror_normal_at_zero_degrees'].message_type = point3f__pb2._POINT3F
_MIRRORSYSTEM.fields_by_name['mirror_angle_range'].message_type = range2f__pb2._RANGE2F
_MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR.containing_type = _MIRRORACTUATORMAPPING
_MIRRORACTUATORMAPPING_QUADRATICMODEL.containing_type = _MIRRORACTUATORMAPPING
_MIRRORACTUATORMAPPING.fields_by_name['transformation_type'].enum_type = _MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE
_MIRRORACTUATORMAPPING.fields_by_name['actuator_angle_pair_vec'].message_type = _MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR
_MIRRORACTUATORMAPPING.fields_by_name['quadratic_model'].message_type = _MIRRORACTUATORMAPPING_QUADRATICMODEL
_MIRRORACTUATORMAPPING.fields_by_name['hall_code_range'].message_type = range2f__pb2._RANGE2F
_MIRRORACTUATORMAPPING_TRANSFORMATIONTYPE.containing_type = _MIRRORACTUATORMAPPING
DESCRIPTOR.message_types_by_name['MirrorSystem'] = _MIRRORSYSTEM
DESCRIPTOR.message_types_by_name['MirrorActuatorMapping'] = _MIRRORACTUATORMAPPING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MirrorSystem = _reflection.GeneratedProtocolMessageType('MirrorSystem', (_message.Message,), {
  'DESCRIPTOR' : _MIRRORSYSTEM,
  '__module__' : 'mirror_system_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.MirrorSystem)
  })
_sym_db.RegisterMessage(MirrorSystem)

MirrorActuatorMapping = _reflection.GeneratedProtocolMessageType('MirrorActuatorMapping', (_message.Message,), {

  'ActuatorAnglePair' : _reflection.GeneratedProtocolMessageType('ActuatorAnglePair', (_message.Message,), {
    'DESCRIPTOR' : _MIRRORACTUATORMAPPING_ACTUATORANGLEPAIR,
    '__module__' : 'mirror_system_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.MirrorActuatorMapping.ActuatorAnglePair)
    })
  ,

  'QuadraticModel' : _reflection.GeneratedProtocolMessageType('QuadraticModel', (_message.Message,), {
    'DESCRIPTOR' : _MIRRORACTUATORMAPPING_QUADRATICMODEL,
    '__module__' : 'mirror_system_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.MirrorActuatorMapping.QuadraticModel)
    })
  ,
  'DESCRIPTOR' : _MIRRORACTUATORMAPPING,
  '__module__' : 'mirror_system_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.MirrorActuatorMapping)
  })
_sym_db.RegisterMessage(MirrorActuatorMapping)
_sym_db.RegisterMessage(MirrorActuatorMapping.ActuatorAnglePair)
_sym_db.RegisterMessage(MirrorActuatorMapping.QuadraticModel)


_MIRRORACTUATORMAPPING_QUADRATICMODEL.fields_by_name['model_coeffs']._options = None
# @@protoc_insertion_point(module_scope)
