# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_characterization.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_characterization.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dsensor_characterization.proto\x12\x04ltpb\"\x8e\x04\n\x16SensorCharacterization\x12\x13\n\x0b\x62lack_level\x18\x01 \x02(\x02\x12\x13\n\x0bwhite_level\x18\x02 \x02(\x02\x12\x13\n\x0b\x63liff_slope\x18\x03 \x01(\x02\x12=\n\tvst_model\x18\x04 \x03(\x0b\x32*.ltpb.SensorCharacterization.VstNoiseModel\x1a\xf5\x02\n\rVstNoiseModel\x12\x0c\n\x04gain\x18\x01 \x02(\r\x12\x11\n\tthreshold\x18\x02 \x02(\x02\x12\r\n\x05scale\x18\x03 \x02(\x02\x12@\n\x03red\x18\x04 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12\x42\n\x05green\x18\x05 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12\x41\n\x04\x62lue\x18\x06 \x02(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x12I\n\x0cpanchromatic\x18\x07 \x01(\x0b\x32\x33.ltpb.SensorCharacterization.VstNoiseModel.VstModel\x1a \n\x08VstModel\x12\t\n\x01\x61\x18\x01 \x02(\x02\x12\t\n\x01\x62\x18\x02 \x02(\x02'
)




_SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL = _descriptor.Descriptor(
  name='VstModel',
  full_name='ltpb.SensorCharacterization.VstNoiseModel.VstModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='ltpb.SensorCharacterization.VstNoiseModel.VstModel.a', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='ltpb.SensorCharacterization.VstNoiseModel.VstModel.b', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=566,
)

_SENSORCHARACTERIZATION_VSTNOISEMODEL = _descriptor.Descriptor(
  name='VstNoiseModel',
  full_name='ltpb.SensorCharacterization.VstNoiseModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gain', full_name='ltpb.SensorCharacterization.VstNoiseModel.gain', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='ltpb.SensorCharacterization.VstNoiseModel.threshold', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='ltpb.SensorCharacterization.VstNoiseModel.scale', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='red', full_name='ltpb.SensorCharacterization.VstNoiseModel.red', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='green', full_name='ltpb.SensorCharacterization.VstNoiseModel.green', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue', full_name='ltpb.SensorCharacterization.VstNoiseModel.blue', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='panchromatic', full_name='ltpb.SensorCharacterization.VstNoiseModel.panchromatic', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=566,
)

_SENSORCHARACTERIZATION = _descriptor.Descriptor(
  name='SensorCharacterization',
  full_name='ltpb.SensorCharacterization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='black_level', full_name='ltpb.SensorCharacterization.black_level', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='white_level', full_name='ltpb.SensorCharacterization.white_level', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cliff_slope', full_name='ltpb.SensorCharacterization.cliff_slope', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vst_model', full_name='ltpb.SensorCharacterization.vst_model', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SENSORCHARACTERIZATION_VSTNOISEMODEL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=566,
)

_SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL.containing_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL
_SENSORCHARACTERIZATION_VSTNOISEMODEL.fields_by_name['red'].message_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL
_SENSORCHARACTERIZATION_VSTNOISEMODEL.fields_by_name['green'].message_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL
_SENSORCHARACTERIZATION_VSTNOISEMODEL.fields_by_name['blue'].message_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL
_SENSORCHARACTERIZATION_VSTNOISEMODEL.fields_by_name['panchromatic'].message_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL
_SENSORCHARACTERIZATION_VSTNOISEMODEL.containing_type = _SENSORCHARACTERIZATION
_SENSORCHARACTERIZATION.fields_by_name['vst_model'].message_type = _SENSORCHARACTERIZATION_VSTNOISEMODEL
DESCRIPTOR.message_types_by_name['SensorCharacterization'] = _SENSORCHARACTERIZATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorCharacterization = _reflection.GeneratedProtocolMessageType('SensorCharacterization', (_message.Message,), {

  'VstNoiseModel' : _reflection.GeneratedProtocolMessageType('VstNoiseModel', (_message.Message,), {

    'VstModel' : _reflection.GeneratedProtocolMessageType('VstModel', (_message.Message,), {
      'DESCRIPTOR' : _SENSORCHARACTERIZATION_VSTNOISEMODEL_VSTMODEL,
      '__module__' : 'sensor_characterization_pb2'
      # @@protoc_insertion_point(class_scope:ltpb.SensorCharacterization.VstNoiseModel.VstModel)
      })
    ,
    'DESCRIPTOR' : _SENSORCHARACTERIZATION_VSTNOISEMODEL,
    '__module__' : 'sensor_characterization_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.SensorCharacterization.VstNoiseModel)
    })
  ,
  'DESCRIPTOR' : _SENSORCHARACTERIZATION,
  '__module__' : 'sensor_characterization_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.SensorCharacterization)
  })
_sym_db.RegisterMessage(SensorCharacterization)
_sym_db.RegisterMessage(SensorCharacterization.VstNoiseModel)
_sym_db.RegisterMessage(SensorCharacterization.VstNoiseModel.VstModel)


# @@protoc_insertion_point(module_scope)
