# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tof_calibration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tof_calibration.proto',
  package='ltpb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15tof_calibration.proto\x12\x04ltpb\"x\n\x0eToFCalibration\x12\x17\n\x0foffset_distance\x18\x01 \x02(\x02\x12\x1a\n\x12offset_measurement\x18\x02 \x02(\x02\x12\x16\n\x0extalk_distance\x18\x03 \x02(\x02\x12\x19\n\x11xtalk_measurement\x18\x04 \x02(\x02'
)




_TOFCALIBRATION = _descriptor.Descriptor(
  name='ToFCalibration',
  full_name='ltpb.ToFCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset_distance', full_name='ltpb.ToFCalibration.offset_distance', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset_measurement', full_name='ltpb.ToFCalibration.offset_measurement', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xtalk_distance', full_name='ltpb.ToFCalibration.xtalk_distance', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xtalk_measurement', full_name='ltpb.ToFCalibration.xtalk_measurement', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['ToFCalibration'] = _TOFCALIBRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToFCalibration = _reflection.GeneratedProtocolMessageType('ToFCalibration', (_message.Message,), {
  'DESCRIPTOR' : _TOFCALIBRATION,
  '__module__' : 'tof_calibration_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.ToFCalibration)
  })
_sym_db.RegisterMessage(ToFCalibration)


# @@protoc_insertion_point(module_scope)
